name    'xformation-stash_backup_client'
version '0.1.2'
source 'https://github.com/x-formation/'
author 'mwitowski@x-formation.com'
license 'Apache License, Version 2.0'
summary 'Puppet module for Stash Backup Client'
description 'This module installs the client for Stash'
dependency 'torrancew/cron', '>= 0.1.0'
